name: droopler
recipe: drupal9
config:
  # Droopler project webroot.
  webroot: ./web
  drush: 11

services:
  node:
    type: node
    globals:
      gulp-cli: "latest"

tooling:
  npm-theme:
    service: node
    description: Runs npm on the subtheme.
    cmd: npm
    dir: /app/web/profiles/contrib/droopler/themes/custom/droopler_theme
  gulp-theme:
    service: node
    description: Runs gulp on the theme.
    cmd: gulp
    dir: /app/web/profiles/contrib/droopler/themes/custom/droopler_theme
  npm-subtheme:
    service: node
    description: Runs npm on the subtheme.
    cmd: npm
    dir: /app/web/themes/custom/droopler_subtheme
  gulp-subtheme:
    service: node
    description: Runs gulp on the subtheme.
    cmd: gulp
    dir: /app/web/themes/custom/droopler_subtheme
  build-full-profile:
    description: Builds the full profile (all modules + demo content) from the scratch.
    cmd:
      - appserver: composer install
      - node: cd /app/web/profiles/contrib/droopler/themes/custom/droopler_theme && npm install
      - node: cd /app/web/themes/custom/droopler_subtheme && npm install
      - node: cd /app/web/profiles/contrib/droopler/themes/custom/droopler_theme && gulp compile
      - node: cd /app/web/themes/custom/droopler_subtheme && gulp compile
      - appserver: drush site-install droopler install_configure_form.enable_update_status_module=TRUE install_configure_form.enable_update_status_emails=NULL --db-url='mysql://drupal9:drupal9@database/drupal9' --account-name=admin --account-pass=123 --site-name=droopler -y --locale=en droopler_additional_modules_form.module_d_blog=1 droopler_additional_modules_form.module_d_product=1 droopler_additional_modules_form.init_content=1 droopler_additional_modules_form.documentation=1
  build-bare-profile:
    description: Builds the bare profile (without demo content) from the scratch.
    cmd:
      - appserver: composer install
      - node: cd /app/web/profiles/contrib/droopler/themes/custom/droopler_theme && npm install
      - node: cd /app/web/themes/custom/droopler_subtheme && npm install
      - node: cd /app/web/profiles/contrib/droopler/themes/custom/droopler_theme && gulp compile
      - node: cd /app/web/themes/custom/droopler_subtheme && gulp compile
      - appserver: drush site-install droopler install_configure_form.enable_update_status_module=TRUE install_configure_form.enable_update_status_emails=NULL --db-url='mysql://drupal9:drupal9@database/drupal9' --account-name=admin --account-pass=123 --site-name=droopler -y --locale=en
  prepare:
    description: Prepares the codebase by downloading all vendors and compiling assets.
    cmd:
      - appserver: composer install
      - node: cd /app/web/profiles/contrib/droopler/themes/custom/droopler_theme && npm install
      - node: cd /app/web/themes/custom/droopler_subtheme && npm install
      - node: cd /app/web/profiles/contrib/droopler/themes/custom/droopler_theme && gulp compile
      - node: cd /app/web/themes/custom/droopler_subtheme && gulp compile
  
